export const CLASSIC_TILE_SIZE = 32
export const CLASSIC_SIMULATION_HZ = 60
export const CLASSIC_MAX_CATCH_UP_STEPS = 8
export const CLASSIC_PLAYER_WIDTH = 22
export const CLASSIC_PLAYER_STANDING_HEIGHT = 44
export const CLASSIC_PLAYER_CROUCHING_HEIGHT = 22
