/* 自定义关卡 */
const LEVEL_6 = {
  name: '自定义关卡',
  width: 135,
  cellType: 3,
  winCondition: WIN_COLLECT_ALL,
  sky: [C.sky2, '#e8a0a0'],
  map: [
      "                                                                                                                                       ",
      "                                                                                                                                       ",
      "                                                                                                                                       ",
      "                                                                                                                                       ",
      "                                                                                                                                       ",
      "                                                                                                                                       ",
      "                                                                                                                                       ",
      "                                                                                                                                       ",
      "                                                                                                                                       ",
      "                                                                                                                                       ",
      "                                                                                                                                       ",
      "                                                                                                                                       ",
      "P                                                                                                                                      ",
      "########### # ####      F                                                                                                              ",
      "############### ##########                                                                                                             ",
  ],
  floatPlatforms: [],
  pipeSpawners: [],
  tutorials: [],
  knowledgeCards: [],
};
